### ISSUE TITLE
plist gem not installed by default

### ISSUE THREAD

**Issue by fklingler** [zhaocai/alfred2-ruby-template#1]
The `plist` gem does not seem to be installed by default, it would be useful to add a Gemfile to the root directory, and instructions in the Quick Start Guide

**Comment by zhaocai** [comment]
'plist' is going to be installed by alfred-workflow gem

**Comment by fklingler** [comment]
Yes but the `rake install` will fail, if you follow the quick start guide, since `plist` is used and `alfred-worklow` is not already installed !

**Comment by zhaocai** [comment]
fixed. thanks.
