### ISSUE TITLE
ruby version forced when cloning repo

### ISSUE THREAD

**Issue by olibob** [zhaocai/alfred2-ruby-template#4]
Hi,

I just cloned your repo following http://zhaocai.github.io/alfred2-ruby-template/
The '.ruby-version' file forces the system ruby to be used whatever that might be.

I was confused at first because I lost my gemset and more recent ruby version (rvm).

Would you consider adding the '.ruby-version' to your '.gitignore' file?

This would prevent others to run into the same issue I just had.

Regards,

**Comment by zhaocai** [comment]
done!
